### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by chargeflux** [DrabWeb/Komikan#3]
I am on OS X El Capitan and there seems to be an issue with memory usage.  When browsing through a manga, the memory usage climbs to significant levels and even if I close the manga viewer, Komikan continues to use the same amount of memory and doesn't drop down to what it was at launch (~150 mb). Once it got so bad that it started using 20 GB of RAM (I have a 8 GB MBP 2015) and locked up my system due to insufficient application memory. Thus, I would have to quit the application regularly to recoup the memory locked up.

Any support would be appreciated!

**Comment by DrabWeb** [comment]
Yeah when I made this I didnt know how to properly do memory management, so it doesnt free up the memory after say a manga is closed. I will definitely look into this later. How many manga do you have imported?

**Comment by KaitoZero76** [comment]
I have 50 manga so far, most of them are 40 pages or so and some are 200+ pages.

**Comment by DrabWeb** [comment]
How many manga do you open before it starts taking up too much memory?

**Comment by KaitoZero76** [comment]
The memory increases whether I have a small or large manga open. It just keeps increasing as I read through the manga and when I close the manga the memory doesn't drop. I leafed through a small manga and a large manga (separately, one at a time) just now and it is right now consuming 1.14 GB of memory after closing the viewer.

**Comment by DrabWeb** [comment]
I can almost guarantee this is because it keeps manga pages in memory even when the reader is closed, I will try to fix this when I work more on Komikan

**Comment by KaitoZero76** [comment]
That would make sense. Looking forward to the next update!
