### ISSUE TITLE
Bookmarks/Chapters

### ISSUE THREAD

**Issue by chargeflux** [DrabWeb/Komikan#4]
Are there any plans to add chapter support? I noticed that there is an option to add bookmarks but where is that information stored? I tried exporting the metadata but information about bookmarks doesn't show up in the JSON file. Is there a particular key I can use to specify pages as bookmarks (acting as pseudo chapters essentially) in the JSON file so Komikan can recognize it? 

Thank you!

**Comment by DrabWeb** [comment]
I guess when making this I forgot to add bookmark support into the JSON, Ill have it added for the next release. As for the volumes/chapters metadata, I think it would be a good idea, but I cant say for sure when it will get added.
